-- MySQL Script generated by MySQL Workbench
-- Wed Dec  6 23:49:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Transporte
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Transporte
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Transporte` DEFAULT CHARACTER SET utf8 ;
USE `Transporte` ;

-- -----------------------------------------------------
-- Table `Transporte`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Transporte`.`cliente` (
  `codigo_cliente` VARCHAR(15) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `rg` VARCHAR(15) NULL,
  `nome` VARCHAR(80) NULL,
  `celular` VARCHAR(15) NULL,
  `telefone` VARCHAR(15) NULL,
  PRIMARY KEY (`codigo_cliente`, `cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transporte`.`tipo_funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Transporte`.`tipo_funcionario` (
  `codigo_tipo_funcionario` INT NOT NULL,
  `cargo` VARCHAR(45) NULL,
  `modulo_venda` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo_tipo_funcionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transporte`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Transporte`.`funcionario` (
  `codigo_funcionario` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `cpf` VARCHAR(45) NULL,
  `rg` VARCHAR(45) NULL,
  `cnh` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `celular` VARCHAR(45) NULL,
  `data_nascimento` VARCHAR(45) NULL,
  `rua` VARCHAR(45) NULL,
  `numero` INT NULL,
  `cidade` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `email` VARCHAR(100) NULL,
  `tipo_funcionario` INT NOT NULL,
  `senha_acesso` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo_funcionario`, `tipo_funcionario`),
  CONSTRAINT `fk_funcionario_tipo_funcionario`
    FOREIGN KEY (`tipo_funcionario`)
    REFERENCES `Transporte`.`tipo_funcionario` (`codigo_tipo_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_funcionario_tipo_funcionario_idx` ON `Transporte`.`funcionario` (`tipo_funcionario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Transporte`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Transporte`.`cidade` (
  `codigo_cidade` INT NOT NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo_cidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transporte`.`tipo_onibus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Transporte`.`tipo_onibus` (
  `codigo_tipo_onibus` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `qtd_poltrona` INT NULL,
  PRIMARY KEY (`codigo_tipo_onibus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Transporte`.`onibus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Transporte`.`onibus` (
  `codigo_onibus` INT NOT NULL,
  `placa` VARCHAR(45) NULL,
  `tipo_onibus` INT NOT NULL,
  PRIMARY KEY (`codigo_onibus`, `tipo_onibus`),
  CONSTRAINT `fk_onibus_tipo_onibus1`
    FOREIGN KEY (`tipo_onibus`)
    REFERENCES `Transporte`.`tipo_onibus` (`codigo_tipo_onibus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_onibus_tipo_onibus1_idx` ON `Transporte`.`onibus` (`tipo_onibus` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Transporte`.`poltrona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Transporte`.`poltrona` (
  `codigo_poltrona` INT NOT NULL,
  `status` INT NULL,
  `numero` INT NULL,
  `codigo_onibus` INT NOT NULL,
  PRIMARY KEY (`codigo_poltrona`, `codigo_onibus`),
  CONSTRAINT `fk_poltrona_onibus1`
    FOREIGN KEY (`codigo_onibus`)
    REFERENCES `Transporte`.`onibus` (`codigo_onibus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_poltrona_onibus1_idx` ON `Transporte`.`poltrona` (`codigo_onibus` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Transporte`.`itinerario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Transporte`.`itinerario` (
  `codigo_itinerario` INT NOT NULL,
  `valor` FLOAT NULL,
  `qtd_paradas` INT NULL,
  `local_embarque` VARCHAR(45) NULL,
  `local_desembarque` VARCHAR(45) NULL,
  `data_embarque` VARCHAR(45) NULL,
  `cidade_embarque` INT NOT NULL,
  `cidade_desembarque` INT NOT NULL,
  `codigo_onibus` INT NOT NULL,
  PRIMARY KEY (`codigo_itinerario`, `codigo_onibus`),
  CONSTRAINT `fk_itinerario_cidade1`
    FOREIGN KEY (`cidade_embarque`)
    REFERENCES `Transporte`.`cidade` (`codigo_cidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itinerario_onibus1`
    FOREIGN KEY (`codigo_onibus`)
    REFERENCES `Transporte`.`onibus` (`codigo_onibus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_itinerario_cidade1_idx` ON `Transporte`.`itinerario` (`cidade_embarque` ASC) VISIBLE;

CREATE INDEX `fk_itinerario_onibus1_idx` ON `Transporte`.`itinerario` (`codigo_onibus` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Transporte`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Transporte`.`venda` (
  `codigo_venda` INT NOT NULL,
  `codigo_cliente` VARCHAR(15) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo_venda`, `codigo_cliente`, `cpf`),
  CONSTRAINT `fk_venda_cliente1`
    FOREIGN KEY (`codigo_cliente` , `cpf`)
    REFERENCES `Transporte`.`cliente` (`codigo_cliente` , `cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_venda_cliente1_idx` ON `Transporte`.`venda` (`codigo_cliente` ASC, `cpf` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
