package view;

import java.awt.event.WindowEvent;
import model.Cidade;
import model.Onibus;
import model.Itinerario;
/**
 *
 * @author Aline e Ruan
 */
public class JFrameItinerarioCRUD extends javax.swing.JFrame {
    
    private Cidade cidade;
    private Onibus onibus;
    private Itinerario itinerario;
    private boolean disconnectOnClose;

    /**
     * Creates new form JFrameItinerarioCRUD
     */
    
    public JFrameItinerarioCRUD(Itinerario itinerario, boolean disconnectOnClose) throws Exception {
        initComponents();
        if( itinerario == null ) {
            this.itinerario = new Itinerario();
        } else {
            this.itinerario = itinerario;
            dataUp();
            jTextFieldCodigoItinerario.setEnabled(false);
        }
        this.disconnectOnClose = disconnectOnClose;
    }
    
     private void dataUp() {
        // data.getter
        // java.swing.setter
        
        jTextFieldCodigoItinerario.setText( String.valueOf( itinerario.getCodigoItinerario()) );
        jTextFieldCodigoOnibus.setText( itinerario.getOnibus());        
        jTextFieldValor.setText( itinerario.getValor());
        jTextFieldOrigem.setText( itinerario.getOrigem());
        jTextFieldEmissor.setText( itinerario.getOrgaoEmissor() );
        jTextFieldCpf.setText( itinerario.getNumeroCpf() );
        jTextFieldEndereco.setText( itinerario.getEndereco() );
        jTextFieldNumero.setText( usuario.getNumero() );
        jTextFieldComplemento.setText( usuario.getComplemento() );
        jTextFieldBairro.setText( usuario.getBairro() );
        jTextFieldCidade.setText( usuario.getCidade() );
        jTextFieldEstado.setText( usuario.getEstado() );
        jTextFieldTelefone.setText( usuario.getTelefone() );
        jTextFieldCelular.setText( usuario.getCelular() );
        jTextFieldEmail.setText( usuario.getEmail() );
        jTextFieldCrm.setText( usuario.getCrm() ); 
        
        jPasswordFieldSenha.setText( usuario.getSenhaAcesso() );
                
        if( itinerario.getTipoUsuario().getNome() != null ) {
            jTextFieldTipoUsuario.setText( usuario.getTipoUsuario().getNome() );
        }
        
        if( usuario.getConvenio() != null ) {
            jTextFieldConvenio.setText( usuario.getConvenio().getEmpresaConvenio() );
        }
        
        if( usuario.getEspecialidade() != null ) {
            jTextFieldEspecialidade.setText( usuario.getEspecialidade().getDescricaoEspecialidade() );
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldCodigoItinerario = new javax.swing.JTextField();
        jLabelCodigo = new javax.swing.JLabel();
        jLabelLocalEmbarque = new javax.swing.JLabel();
        jTextFieldLocalEmbarque = new javax.swing.JTextField();
        jLabelLocalDesembarque = new javax.swing.JLabel();
        jTextFieldLocalDesembarque = new javax.swing.JTextField();
        jLabelValor = new javax.swing.JLabel();
        jTextFieldValor = new javax.swing.JTextField();
        jLabelCodigoOnibus = new javax.swing.JLabel();
        jTextFieldCodigoOnibus = new javax.swing.JTextField();
        jLabelOrigem = new javax.swing.JLabel();
        jTextFieldOrigem = new javax.swing.JTextField();
        jLabelDestino = new javax.swing.JLabel();
        jTextFieldDestino = new javax.swing.JTextField();
        jLabelEmbarque = new javax.swing.JLabel();
        jTextFieldEmbarque = new javax.swing.JTextField();
        jLabelQtdParadas = new javax.swing.JLabel();
        jTextFieldQtdParadas = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonApagar = new javax.swing.JButton();
        jButtonBuscaOrigem = new javax.swing.JButton();
        jButtonBuscaDestino = new javax.swing.JButton();
        jButtonBuscaCodigoOnibus = new javax.swing.JButton();
        jButtonApagaCodigoOnibus = new javax.swing.JButton();
        jButtonApagaDestino = new javax.swing.JButton();
        jButtonApagaOrigem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Itinerários");

        jLabelCodigo.setText("Código");

        jLabelLocalEmbarque.setText("Local de Embarque");

        jLabelLocalDesembarque.setText("Local de Desembarque");

        jLabelValor.setText("Valor");

        jLabelCodigoOnibus.setText("Código Ônibus");

        jLabelOrigem.setText("Origem");

        jTextFieldOrigem.setEditable(false);

        jLabelDestino.setText("Destino");

        jTextFieldDestino.setEditable(false);

        jLabelEmbarque.setText("Data de Embarque");

        jLabelQtdParadas.setText("Quantidade de Paradas");

        jButtonSalvar.setText("Salvar");

        jButtonApagar.setText("Apagar");

        jButtonBuscaOrigem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/search-icon.png"))); // NOI18N
        jButtonBuscaOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscaOrigemActionPerformed(evt);
            }
        });

        jButtonBuscaDestino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/search-icon.png"))); // NOI18N

        jButtonBuscaCodigoOnibus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/search-icon.png"))); // NOI18N

        jButtonApagaCodigoOnibus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/eraser-icon.png"))); // NOI18N
        jButtonApagaCodigoOnibus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagaCodigoOnibusActionPerformed(evt);
            }
        });

        jButtonApagaDestino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/eraser-icon.png"))); // NOI18N
        jButtonApagaDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagaDestinoActionPerformed(evt);
            }
        });

        jButtonApagaOrigem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/eraser-icon.png"))); // NOI18N
        jButtonApagaOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagaOrigemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCodigo)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCodigoItinerario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabelQtdParadas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldQtdParadas, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelCodigoOnibus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCodigoOnibus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuscaCodigoOnibus))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabelOrigem)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonBuscaOrigem))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelEmbarque)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldEmbarque, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonApagaOrigem))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelLocalEmbarque)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldLocalEmbarque, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelLocalDesembarque)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldLocalDesembarque, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonSalvar)
                                .addGap(31, 31, 31)
                                .addComponent(jButtonApagar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelDestino)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonBuscaDestino)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonApagaDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonApagaCodigoOnibus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCodigoItinerario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCodigo)
                            .addComponent(jLabelQtdParadas)
                            .addComponent(jTextFieldQtdParadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCodigoOnibus)
                            .addComponent(jTextFieldCodigoOnibus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelValor)
                            .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jButtonBuscaCodigoOnibus))
                    .addComponent(jButtonApagaCodigoOnibus, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLocalEmbarque)
                    .addComponent(jTextFieldLocalEmbarque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLocalDesembarque)
                    .addComponent(jTextFieldLocalDesembarque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonApagaDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelOrigem)
                        .addComponent(jTextFieldOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelDestino)
                        .addComponent(jTextFieldDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonBuscaOrigem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonBuscaDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonApagaOrigem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldEmbarque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmbarque)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonSalvar)
                        .addComponent(jButtonApagar)))
                .addGap(31, 31, 31))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscaOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscaOrigemActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonBuscaOrigemActionPerformed

    private void jButtonApagaCodigoOnibusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagaCodigoOnibusActionPerformed
        // TODO add your handling code here:
        codigoOnibus = null;
        jTextFieldTipoUsuario.setText( null );
    }//GEN-LAST:event_jButtonApagaCodigoOnibusActionPerformed

    private void jButtonApagaDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagaDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonApagaDestinoActionPerformed

    private void jButtonApagaOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagaOrigemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonApagaOrigemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameItinerarioCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameItinerarioCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameItinerarioCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameItinerarioCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameItinerarioCRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonApagaCodigoOnibus;
    private javax.swing.JButton jButtonApagaDestino;
    private javax.swing.JButton jButtonApagaOrigem;
    private javax.swing.JButton jButtonApagar;
    private javax.swing.JButton jButtonBuscaCodigoOnibus;
    private javax.swing.JButton jButtonBuscaDestino;
    private javax.swing.JButton jButtonBuscaOrigem;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelCodigoOnibus;
    private javax.swing.JLabel jLabelDestino;
    private javax.swing.JLabel jLabelEmbarque;
    private javax.swing.JLabel jLabelLocalDesembarque;
    private javax.swing.JLabel jLabelLocalEmbarque;
    private javax.swing.JLabel jLabelOrigem;
    private javax.swing.JLabel jLabelQtdParadas;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JTextField jTextFieldCodigoItinerario;
    private javax.swing.JTextField jTextFieldCodigoOnibus;
    private javax.swing.JTextField jTextFieldDestino;
    private javax.swing.JTextField jTextFieldEmbarque;
    private javax.swing.JTextField jTextFieldLocalDesembarque;
    private javax.swing.JTextField jTextFieldLocalEmbarque;
    private javax.swing.JTextField jTextFieldOrigem;
    private javax.swing.JTextField jTextFieldQtdParadas;
    private javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables
}




